services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app  # Mount current directory
      - ./db:/app/db  # Ensure SQLite database directory is mounted

volumes:
  db_data:
