services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app  # Mount current directory to keep code in sync
      - db_data:/app/db  # Persist SQLite database in the 'db' folder

volumes:
  db_data:
