services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app  # Mount the current directory into the container
      - ./db:/app/db  # Ensure the database directory is mounted properly

volumes:
  db_data:
