services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app  # Mount current directory to /app inside the container
      - ./db:/app/db  # Persist SQLite database in the 'db' directory

volumes:
  db_data:
